# Generated by Django 4.2.1 on 2023-09-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startseller', '0003_remove_sellerproduct_lastprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
