# Generated by Django 4.2.1 on 2023-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startseller', '0004_sellerproduct_discount_sellerproduct_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
