# Generated by Django 4.2.1 on 2023-09-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startseller', '0006_sellerproduct_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='Seller',
            field=models.TextField(blank=True),
        ),
    ]
