# Generated by Django 4.2.1 on 2023-09-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startseller', '0007_sellerproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='Seller',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
